### ISSUE TITLE
NoClassDefFoundError: scala/tools/scalap/scalax/rules/scalasig/ScalaSigSymbol on project generation

### ISSUE THREAD

**Issue by matthughes** [orrsella/sbt-sublime#14]
I frequently get the following when I run gen-sublime.

It resolves and downloads all the source directories but blows up just as it's writing the project.

```
info] Adding the following to external libraries:
....
[info] Extracting jars to external sources directory
[info] Marking all files in sources directory as read-only
[info] Writing project to file: /Users/mhughes/monitoring.sublime-project
java.lang.NoClassDefFoundError: scala/tools/scalap/scalax/rules/scalasig/ScalaSigSymbol
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:123)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:122)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:122)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:116)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:116)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:156)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:50)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
	at org.json4s.reflect.package$Memo.apply(package.scala:39)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:44)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:91)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:180)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:67)
	at org.json4s.Extraction$.decompose(Extraction.scala:194)
	at com.orrsella.sbtsublime.SublimeProject.toFile(SublimeProject.scala:37)
	at com.orrsella.sbtsublime.SublimePlugin$.doCommand(SublimePlugin.scala:116)
	at com.orrsella.sbtsublime.SublimePlugin$$anonfun$sublimeCommand$1.apply(SublimePlugin.scala:52)
	at com.orrsella.sbtsublime.SublimePlugin$$anonfun$sublimeCommand$1.apply(SublimePlugin.scala:52)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:19)
	at xsbt.boot.Boot$.runImpl(Boot.scala:44)
	at xsbt.boot.Boot$.main(Boot.scala:20)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: scala.tools.scalap.scalax.rules.scalasig.ScalaSigSymbol
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:123)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:122)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:122)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:116)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:116)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:156)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:50)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
	at org.json4s.reflect.package$Memo.apply(package.scala:39)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:44)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:91)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:180)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:67)
	at org.json4s.Extraction$.decompose(Extraction.scala:194)
	at com.orrsella.sbtsublime.SublimeProject.toFile(SublimeProject.scala:37)
	at com.orrsella.sbtsublime.SublimePlugin$.doCommand(SublimePlugin.scala:116)
	at com.orrsella.sbtsublime.SublimePlugin$$anonfun$sublimeCommand$1.apply(SublimePlugin.scala:52)
	at com.orrsella.sbtsublime.SublimePlugin$$anonfun$sublimeCommand$1.apply(SublimePlugin.scala:52)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:19)
	at xsbt.boot.Boot$.runImpl(Boot.scala:44)
	at xsbt.boot.Boot$.main(Boot.scala:20)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: scala/tools/scalap/scalax/rules/scalasig/ScalaSigSymbol
```

**Comment by orrsella** [comment]
Can you please provide some more details?

- Which versions of sbt-sublime and of sbt?
- Does it happen for every project? Did you try with an empty project?
- Did you try removing some of the dependencies you have and see if any particular one causes problems?
- Do you have any of the configuration values available for sbt-sublime set to anything other than the defaults? If so, which values?

Thanks

**Comment by matthughes** [comment]
FWIW, upgrading from 1.0.9 -> 1.1.1 seems to have fixed the problem.  I was using SBT 0.13.9/1.0.9 when I had the problem.

**Comment by orrsella** [comment]
Thanks for the update.
